spring.application.name=online-banking-system
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/online_banking}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:student}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
logging.level.com.onlinebanking=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

app.jwt.secret=${JWT_SECRET:abcdefghijklmnopqrstuvwxyz123456}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.reset-user-data-on-startup=true
