create table bank_users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    role varchar(20) not null,
    created_at timestamp not null
);

create table customer_addresses (
    id bigint generated by default as identity primary key,
    address_line1 varchar(255) not null,
    address_line2 varchar(255),
    city varchar(255) not null,
    state varchar(255) not null,
    postal_code varchar(255) not null,
    country varchar(255) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table customer_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    full_name varchar(255) not null,
    phone_number varchar(255) not null,
    gender varchar(20) not null,
    occupation varchar(255) not null,
    address_id bigint not null unique,
    date_of_birth date not null,
    kyc_status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_customer_profiles_user foreign key (user_id) references bank_users (id),
    constraint fk_customer_profiles_address foreign key (address_id) references customer_addresses (id)
);

create table accounts (
    id bigint generated by default as identity primary key,
    account_number varchar(255) not null unique,
    account_type varchar(20) not null,
    status varchar(20) not null,
    currency_code varchar(3) not null,
    balance numeric(19, 2) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    owner_id bigint not null,
    constraint fk_accounts_owner foreign key (owner_id) references bank_users (id)
);

create index idx_accounts_owner_created_at on accounts (owner_id, created_at);

create table account_number_sequences (
    account_type varchar(20) primary key,
    last_value bigint not null
);

create table account_opening_requests (
    id bigint generated by default as identity primary key,
    requester_id bigint not null,
    account_type varchar(20) not null,
    opening_balance numeric(19, 2) not null,
    status varchar(20) not null,
    approved_account_id bigint unique,
    reviewed_by bigint,
    created_at timestamp not null,
    reviewed_at timestamp,
    constraint fk_account_opening_requests_requester foreign key (requester_id) references bank_users (id),
    constraint fk_account_opening_requests_account foreign key (approved_account_id) references accounts (id),
    constraint fk_account_opening_requests_reviewer foreign key (reviewed_by) references bank_users (id)
);

create index idx_account_opening_requests_status_created_at on account_opening_requests (status, created_at);

create table transactions (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    transaction_reference varchar(255) not null,
    type varchar(30) not null,
    status varchar(20) not null,
    channel varchar(30) not null,
    amount numeric(19, 2) not null,
    counterparty_account_number varchar(255),
    description varchar(255) not null,
    created_at timestamp not null,
    completed_at timestamp,
    constraint fk_transactions_account foreign key (account_id) references accounts (id)
);

create index idx_transactions_account_created_at on transactions (account_id, created_at);

create table ledger_entries (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null,
    entry_type varchar(20) not null,
    amount numeric(19, 2) not null,
    running_balance numeric(19, 2) not null,
    narrative varchar(255) not null,
    created_at timestamp not null,
    constraint fk_ledger_entries_transaction foreign key (transaction_id) references transactions (id)
);

create index idx_ledger_entries_transaction_created_at on ledger_entries (transaction_id, created_at);

create table beneficiaries (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    nickname varchar(255) not null,
    account_number varchar(255) not null,
    active boolean not null,
    created_at timestamp not null,
    constraint uk_beneficiaries_owner_account unique (owner_id, account_number),
    constraint fk_beneficiaries_owner foreign key (owner_id) references bank_users (id)
);

create index idx_beneficiaries_owner_created_at on beneficiaries (owner_id, created_at);

create table audit_logs (
    id bigint generated by default as identity primary key,
    actor_username varchar(255) not null,
    action varchar(255) not null,
    entity_type varchar(255) not null,
    entity_id varchar(255),
    details varchar(1000) not null,
    created_at timestamp not null
);

create index idx_audit_logs_actor_created_at on audit_logs (actor_username, created_at);
