alter table bank_users add column email_hash varchar(64);
update bank_users set email_hash = email;
alter table bank_users alter column email set data type varchar(1024);
alter table bank_users alter column email_hash set not null;
alter table bank_users add constraint uk_bank_users_email_hash unique (email_hash);
alter table bank_users add column failed_login_attempts integer not null default 0;
alter table bank_users add column locked_until timestamp;

alter table customer_profiles add column customer_id varchar(64);
update customer_profiles set customer_id = 'CIF-' || id;
alter table customer_profiles alter column customer_id set not null;
alter table customer_profiles add constraint uk_customer_profiles_customer_id unique (customer_id);
alter table customer_profiles alter column full_name set data type varchar(1024);
alter table customer_profiles alter column phone_number set data type varchar(1024);
alter table customer_profiles add column phone_number_hash varchar(64);
update customer_profiles set phone_number_hash = cast(id as varchar(64));
alter table customer_profiles alter column phone_number_hash set not null;
alter table customer_profiles add column version bigint default 0 not null;

alter table customer_addresses alter column address_line1 set data type varchar(1024);
alter table customer_addresses alter column address_line2 set data type varchar(1024);
alter table customer_addresses alter column city set data type varchar(1024);
alter table customer_addresses alter column state set data type varchar(1024);
alter table customer_addresses alter column postal_code set data type varchar(1024);
alter table customer_addresses alter column country set data type varchar(1024);

alter table accounts add column account_id varchar(64);
update accounts set account_id = 'ACC-' || id;
alter table accounts alter column account_id set not null;
alter table accounts add constraint uk_accounts_account_id unique (account_id);
alter table accounts add column version bigint default 0 not null;

alter table beneficiaries add column beneficiary_id varchar(64);
update beneficiaries set beneficiary_id = 'BEN-' || id;
alter table beneficiaries alter column beneficiary_id set not null;
alter table beneficiaries add constraint uk_beneficiaries_beneficiary_id unique (beneficiary_id);
alter table beneficiaries add column status varchar(30) not null default 'ACTIVE';
update beneficiaries set status = case when active then 'ACTIVE' else 'REJECTED' end;
alter table beneficiaries add column activation_ready_at timestamp;
alter table beneficiaries add column activation_expires_at timestamp;
alter table beneficiaries add column activated_at timestamp;
alter table beneficiaries add column activation_code_hash varchar(128);
alter table beneficiaries add column version bigint default 0 not null;
alter table beneficiaries drop column active;
create index idx_beneficiaries_owner_status_created_at on beneficiaries (owner_id, status, created_at);

alter table audit_logs add column audit_event_id varchar(64);
update audit_logs set audit_event_id = 'AUD-' || id;
alter table audit_logs alter column audit_event_id set not null;
alter table audit_logs add constraint uk_audit_logs_audit_event_id unique (audit_event_id);
alter table audit_logs add column actor_id varchar(255);
alter table audit_logs add column actor_role varchar(255);
alter table audit_logs add column customer_id varchar(64);
alter table audit_logs add column account_id varchar(64);
alter table audit_logs add column correlation_id varchar(255);
alter table audit_logs add column outcome varchar(255);
update audit_logs set outcome = 'SUCCESS' where outcome is null;
alter table audit_logs add column ip_address varchar(255);
alter table audit_logs add column device_fingerprint varchar(255);
alter table audit_logs add column reason_code varchar(255);
alter table audit_logs add column before_snapshot varchar(2000);
alter table audit_logs add column after_snapshot varchar(2000);

create table user_sessions (
    id bigint generated by default as identity primary key,
    session_id varchar(64) not null unique,
    token_id varchar(64) not null unique,
    user_id bigint not null,
    refresh_token_hash varchar(128) not null,
    device_fingerprint varchar(255) not null,
    ip_address varchar(255) not null,
    created_at timestamp not null,
    expires_at timestamp not null,
    last_used_at timestamp not null,
    revoked_at timestamp,
    constraint fk_user_sessions_user foreign key (user_id) references bank_users (id)
);

create index idx_user_sessions_refresh_token_hash on user_sessions (refresh_token_hash);
