create table account_balances (
    id bigint generated by default as identity primary key,
    account_id bigint not null unique,
    available_balance numeric(19, 2) not null,
    ledger_balance numeric(19, 2) not null,
    updated_at timestamp not null,
    version bigint not null default 0,
    constraint fk_account_balances_account foreign key (account_id) references accounts (id)
);

insert into account_balances (account_id, available_balance, ledger_balance, updated_at, version)
select id, balance, balance, current_timestamp, 0
from accounts;

create index idx_account_balances_account on account_balances (account_id);

create table posting_batches (
    id bigint generated by default as identity primary key,
    posting_batch_id varchar(64) not null unique,
    status varchar(20) not null,
    narrative varchar(255) not null,
    created_at timestamp not null,
    completed_at timestamp
);

create table ledger_postings (
    id bigint generated by default as identity primary key,
    posting_batch_id bigint not null,
    account_id bigint not null,
    entry_type varchar(20) not null,
    amount numeric(19, 2) not null,
    resulting_balance numeric(19, 2) not null,
    narrative varchar(255) not null,
    created_at timestamp not null,
    constraint fk_ledger_postings_batch foreign key (posting_batch_id) references posting_batches (id),
    constraint fk_ledger_postings_account foreign key (account_id) references accounts (id)
);

create index idx_ledger_postings_account_created_at on ledger_postings (account_id, created_at);

create table transfer_records (
    id bigint generated by default as identity primary key,
    transfer_id varchar(64) not null unique,
    idempotency_key varchar(128) not null unique,
    from_account_id bigint not null,
    to_account_id bigint not null,
    beneficiary_id bigint not null,
    posting_batch_id bigint unique,
    channel varchar(30) not null,
    status varchar(30) not null,
    amount numeric(19, 2) not null,
    currency_code varchar(3) not null,
    requested_by varchar(255) not null,
    remarks varchar(255) not null,
    failure_code varchar(255),
    created_at timestamp not null,
    completed_at timestamp,
    version bigint not null default 0,
    constraint fk_transfer_records_from_account foreign key (from_account_id) references accounts (id),
    constraint fk_transfer_records_to_account foreign key (to_account_id) references accounts (id),
    constraint fk_transfer_records_beneficiary foreign key (beneficiary_id) references beneficiaries (id),
    constraint fk_transfer_records_posting_batch foreign key (posting_batch_id) references posting_batches (id)
);

create index idx_transfer_records_status_created_at on transfer_records (status, created_at);

create table outbox_events (
    id bigint generated by default as identity primary key,
    event_id varchar(64) not null unique,
    aggregate_type varchar(255) not null,
    aggregate_id varchar(255) not null,
    event_type varchar(255) not null,
    payload varchar(4000) not null,
    created_at timestamp not null,
    processed_at timestamp
);

create index idx_outbox_events_created_at on outbox_events (created_at);
